apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mbarbhuilb1
  name: mbarbhuilb1
  namespace: mbarbhui-ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: mbarbhuiwebapp #label of pods
  type: NodePort
status:
  loadBalancer: {}
