apiVersion: v1
data:
  WORDPRESS_DB_USER: mbarbhuiuser
  WORDPRESS_DB_HOST: mbarbhuidb  # name of db service
  WORDPRESS_DB_NAME: mbarbhuidb
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mbarbhuiweb-config
  namespace: mbarbhui-ns
